### ISSUE TITLE
Add EDMC option to load missions

### ISSUE THREAD

**Issue by skiedude** [PilotsTradeNetwork/MissionAlertBot#378] opened 2022-10-18 01:32 UTC
In the case of a Gold rush mission, I see CCOs posting their EDMC off pictures. 
Why not have the bot post those to streamline the process?
![edmc_man](https://user-images.githubusercontent.com/6210395/196314313-74103d4a-9ed0-4c38-ab6e-d7692d706f87.jpg)
![EDMC_OFF_Superman](https://user-images.githubusercontent.com/6210395/196314315-3995bd6f-9567-4550-be7a-11c607336542.jpg)

**Comment by cimspin** [comment] 2022-10-18 05:15
duplicate of #296

**Closed** 2022-10-18 06:02 UTC
